version: '2'

services:
  database:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
       - db-data:/config
    restart: unless-stopped

  app:
    image: ruby
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    workdir: /app
    volumes:
      - ./server:/app
    depends_on:
      - database
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails s -b '0.0.0.0'"

volumes: 
  db-data:
