version: '2'

services:
  database:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD}
    volumes:
       - db-data:/config
    restart: unless-stopped

  app:
    image: ruby:3
    restart: unless-stopped
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY}
      MYSQLHOST: ${MYSQLHOST}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      MYSQLDATABASE: ${MYSQLDATABASE}
      TEACHER_EMAIL: ${TEACHER_EMAIL}
      TEACHER_PASSWORD: ${TEACHER_PASSWORD}
      TEACHER_NAME: ${TEACHER_NAME}
      TEACHER_LAST_NAME: ${TEACHER_LAST_NAME}
    ports:
      - ${PORT}:3000
    working_dir: /app
    volumes:
      - ./server:/app
    depends_on:
      - database
    command: ./run.sh

volumes: 
  db-data:
