version: '2'

services:
  database:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
       - db-data:/config
    restart: unless-stopped

  # docker-compose run app rails new . --force --database=mysql --skip-bundle
  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ".:/workspace"
    links:
      - "database"

  phpmyadmin:
    image: 'phpmyadmin'
    depends_on:
      - database
    environment:
      - PMA_HOST=database
    ports:
      - '8080:80'
    restart: unless-stopped

volumes: 
  db-data:
