version: '2'

services:
  database:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
       - db-data:/config
    restart: unless-stopped

  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ".:/workspace"
    links:
      - "database"
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails s -b '0.0.0.0'"

volumes: 
  db-data:
